name: Frontend CI

on:
  workflow_dispatch:
  push:
    paths:
      - "client/**"
  pull_request:
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          # Haven't found any other solution thn --legacy-peer-deps or downgrading npm to fix this :'(
      - run: |
          cd client
          npm ci --legacy-peer-deps
          npm run lint
          npm run build
          npm run storybook:build
